Akismet spam filter
tableflip/post pull request #5
Opened 2017-01-04 14:31 UTC by bmordan

Resolves #4 

This PR adds a basic spam filter in the `POST/:domain*` route. It calls out to the Akismet api and checks the message for spaminess.

If the message is spam, **post** stops and does not add the message to the que. If it's ok then **post** will carry on as usual.

2017-01-04 15:42 UTC, bmordan commented
dependency-ci fail because of jade

2017-01-09 16:18 UTC, olizilla requested changes
Minor changes. Is good stuff.

2017-01-09 16:18 UTC, olizilla commented on emails/spam.js
> +      referrer: value.key
This should probably be the referrer header from the request

2017-01-09 16:18 UTC, olizilla commented on emails/mailer.js
> +    if (!value.headers['X-Spam-Flag']) return
Check for property existance
```js
value.headers.hasOwnProperty('X-Spam-Flag')
```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty

2017-01-09 17:29 UTC, merged